name: pr-checks

on: 
  pull_request:
    branches: [main, feature]
  push:
    branches: [ main ]
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-cov
        python -m pip install python-dateutil
        python -m pip install APScheduler
        python -m pip install requests
        python -m pip install freezegun
        python -m pip install mock

        if [ -f requirements.txt ]; then -m pip install -r requirements.txt; fi

 
    - name: tests with pytest
      run: |
                pytest
    - name: coverage
      run: |
        coverage run -m pytest
        coverage report --fail-under=50    
