- name: executing remote ssh commands using ssh key
  uses: appleboy/ssh-action@master
  with:
    host: ${{ secrets.HOST_DNS }}
    username: ${{ secrets.USERNAME }}
    key: ${{ secrets.EC2_SSH_KEY }}
    #port: ${{ secrets.PORT }}
    script: screen python3.10 ../REMOTE_USER/server.py
