name: executing remote ssh commands using ssh key

on:
  workflow_run:
    workflows: ["Push-to-EC2"]
    types:
      - completed  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_DNS }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        #port: ${{ secrets.PORT }}
        script: screen python3.10 ../REMOTE_USER/server.py
